// <auto-generated>
// Rewired Constants
// This list was generated on 1/27/2019 11:47:55 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

public static partial class RewiredConsts {
    public static partial class Action {
        public static partial class Default {
        }
        public static partial class GamePlay {
            [Rewired.Dev.ActionIdFieldInfo(categoryName = "GamePlay", friendlyName = "Horizontal")]
            public const int Horizontal = 4;
            [Rewired.Dev.ActionIdFieldInfo(categoryName = "GamePlay", friendlyName = "Vertical")]
            public const int Vertical = 5;
            [Rewired.Dev.ActionIdFieldInfo(categoryName = "GamePlay", friendlyName = "Start")]
            public const int Start = 6;
            [Rewired.Dev.ActionIdFieldInfo(categoryName = "GamePlay", friendlyName = "Quit")]
            public const int Quit = 8;
            [Rewired.Dev.ActionIdFieldInfo(categoryName = "GamePlay", friendlyName = "Action0")]
            public const int Action0 = 7;
        }
    }
    public static partial class Category {
        public const int Default = 0;
        public const int GamePlay = 1;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
    }
    public static partial class InputBehavior {
        public const int Default = 0;
    }
    public static partial class CustomController {
    }
}
