// <auto-generated>
// Rewired Constants
// This list was generated on 1/25/2019 9:37:33 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

public static partial class RewiredConsts {
    public static partial class Action {
        public static partial class Default {
        }
        public static partial class GamePlay {
        }
    }
    public static partial class Category {
        public const int Default = 0;
        public const int GamePlay = 1;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
    }
    public static partial class InputBehavior {
        public const int Default = 0;
    }
    public static partial class CustomController {
    }
}
